### PR TITLE
Silence warnings and support execution without root

### PR DESCRIPTION
**Pull request by anarcat**
i made some cosmetic changes to make the collection script runnable as a non-root user, to work around the curl | sudo bash syndrome. :) this is a refactor of #1.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I believe this should be solved differently, by testing if a file exist instead of supressing the warning, and by adding a command line option to print to stdout instead of logging.

**Comment by anarcat** [comment]
okay. what should/could that option be?

what if the collector would just output to stdout and the calling process (cron, pm hooks) would redirect to the logfile? i understand it writes those headers up there, but are those really necessary?

**Comment by petterreinholdtsen** [comment]
Not quite sure what the option should be.  Perhaps if should check if stdin is a tty and log to stdout and the log file in that case?  I do not want the log file name duplicated across cron and pm hooks, so that should stay in the collector script.

**Comment by anarcat** [comment]
makes sense.

**Pull request closed without merging**
